services:
    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - '8080:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./portfolios:/app
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    php:
        image: gameblack/laravel-php:latest
        restart: unless-stopped
        volumes:
            - ./portfolios:/app
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
