services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - /var/www/html:/var/www/html
    command: bash -c "apt-get update && apt-get install -y git unzip libzip-dev libpng-dev libonig-dev libxml2-dev zip && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd && composer install && php-fpm"
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /var/www/html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
