---
- hosts: web
  become: yes
  tasks:
    - name: Installer les dépendances système
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Installer Docker
      shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        creates: /usr/bin/docker

    - name: Installer Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Copier les fichiers de l'application sur le VPS
      synchronize:
        src: ../
        dest: /srv/portfolio/
        recursive: yes
        delete: yes

    - name: Lancer l'application avec Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /srv/portfolio/