---
- hosts: web
  become: yes
  tasks:
    - name: Installer Apache, PHP et rsync
      apt:
        name:
          - apache2
          - php
          - rsync
        state: present
        update_cache: yes

    - name: Déployer le build front
      synchronize:
        src: ../portfolios/dist/
        dest: /var/www/html/
        recursive: yes
        delete: yes

    - name: Déployer le dossier public Laravel
      synchronize:
        src: ../portfolios/public/
        dest: /var/www/html/
        recursive: yes
        delete: yes

    - name: S'assurer qu'Apache est démarré
      service:
        name: apache2
        state: started
        enabled: yes