---
- hosts: web
  become: yes
  tasks:
    - name: Installer Apache, PHP, Composer et rsync
      apt:
        name:
          - apache2
          - php
          - composer
          - rsync
        state: present
        update_cache: yes

    - name: Copier l'application sur le VPS
      synchronize:
        src: ../portfolios/
        dest: /var/www/html/
        recursive: yes
        delete: yes

    - name: Installer les dépendances PHP avec Composer
      command: composer install --no-interaction --prefer-dist --optimize-autoloader
      args:
        chdir: /var/www/html

    - name: Créer le VirtualHost Apache pour la racine
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html/public
              <Directory /var/www/html/public>
                  AllowOverride All
                  Require all granted
              </Directory>
              ErrorLog ${APACHE_LOG_DIR}/error.log
              CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>

    - name: Activer mod_rewrite
      command: a2enmod rewrite

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted