---
- hosts: web
  become: yes
  tasks:
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Installer Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Copier l'application sur le VPS
      synchronize:
        src: ../portfolios/
        dest: /var/www/html/
        recursive: yes
        delete: yes
        rsync_opts:
          - "--exclude=.env"
          - "--exclude=vendor"
          - "--exclude=database/database.sqlite"
    - name: Copier le docker-compose.yml
      copy:
        dest: /home/{{ ansible_user }}/docker-compose.yml
        content: |
          services:
            app:
              image: php:8.2-fpm
              container_name: laravel_app
              working_dir: /var/www/html
              volumes:
                - /var/www/html:/var/www/html
            nginx:
              image: nginx:alpine
              container_name: nginx
              ports:
                - "80:80"
              volumes:
                - /var/www/html:/var/www/html
                - ./nginx.conf:/etc/nginx/conf.d/default.conf
              depends_on:
                - app

    - name: Copier la conf Nginx pour Docker
      copy:
        dest: /home/{{ ansible_user }}/nginx.conf
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html/public;
              index index.php index.html;
              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }
              location ~ \.php$ {
                  fastcgi_pass app:9000;
                  fastcgi_index index.php;
                  fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                  include fastcgi_params;
              }
          }

    - name: Ajouter l'utilisateur au groupe docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Lancer la stack Docker
      shell: docker compose -f /home/{{ ansible_user }}/docker-compose.yml up -d

    - name: Corriger les droits sur storage dans le conteneur
      shell: docker exec laravel_app chown -R www-data:www-data /var/www/html/storage && docker exec laravel_app chmod -R 777 /var/www/html/storage

    - name: Corriger les droits sur bootstrap/cache dans le conteneur
      shell: docker exec laravel_app chown -R www-data:www-data /var/www/html/bootstrap/cache && docker exec laravel_app chmod -R 777 /var/www/html/bootstrap/cache

    - name: Corriger les droits sur database.sqlite dans le conteneur
      shell: docker exec laravel_app chown www-data:www-data /var/www/html/database/database.sqlite && docker exec laravel_app chmod 666 /var/www/html/database/database.sqlite