---
- hosts: web
  become: yes
  tasks:
    - name: Installer Nginx, PHP-FPM, Composer et extensions nécessaires
      apt:
        name:
          - nginx
          - php-fpm
          - php
          - composer
          - rsync
          - php-xml
        state: present
        update_cache: yes

    - name: Copier l'application sur le VPS
      synchronize:
        src: ../portfolios/
        dest: /var/www/html/
        recursive: yes
        delete: yes

    - name: Installer les dépendances PHP avec Composer
      command: composer install --no-interaction --prefer-dist --optimize-autoloader
      args:
        chdir: /var/www/html

    - name: Configurer Nginx pour servir l'app Laravel
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html/public;
              index index.php index.html index.htm;
              server_name _;
              location / {
                  try_files $uri $uri/ /index.php?$query_string;
              }
              location ~ \.php$ {
                  include snippets/fastcgi-php.conf;
                  fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
              }
              location ~ /\.ht {
                  deny all;
              }
          }

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted

    - name: S'assurer que PHP-FPM est démarré
      service:
        name: php*-fpm
        state: started