name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

      - name: Run PHP_CodeSniffer
        run: php phpcs.phar --standard=PSR12 ./portfolios
        continue-on-error: true

  deploy:
    needs: phpcs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/playbook.yml \
            --extra-vars "ansible_host=${{ secrets.VPS_HOST }} ansible_user=${{ secrets.VPS_USER }} ansible_port=22 ansible_ssh_pass=${{ secrets.VPS_PASS }}"