name: PHP_CodeSniffer

on:
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar

      - name: Run PHP_Code Beautifier and Fixer
        run: php phpcbf.phar --standard=PSR12 ./portfolios

      - name: Run PHP_CodeSniffer
        run: php phpcs.phar --standard=PSR12 ./portfolios